parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(APP_DATABASE_URL): ''
    env(POSTGRES_VERSION): '10.10'
    env(MAGNETICOD_DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                url: '%env(resolve:APP_DATABASE_URL)%'
                server_version: '%env(resolve:POSTGRES_VERSION)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            magneticod:
                driver: 'pdo_pgsql'
                url: '%env(resolve:MAGNETICOD_DATABASE_URL)%'
                server_version: '%env(resolve:POSTGRES_VERSION)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                # Opt-in to new mapping driver mode as of Doctrine ORM 2.16, https://github.com/doctrine/orm/pull/10455
                report_fields_where_declared: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            magneticod:
                connection: magneticod
                # Opt-in to new mapping driver mode as of Doctrine ORM 2.16, https://github.com/doctrine/orm/pull/10455
                report_fields_where_declared: true
                mappings:
                    Magnetico:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Magnetico/Entity'
                        prefix: 'App\Magnetico'
                        alias: Magnetico
                dql:
                    string_functions:
                        ILIKE: 'App\Doctrine\ORM\AST\Ilike'
