parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(APP_DATABASE_URL): ''
    env(MAGNETICOD_DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                url: '%env(resolve:APP_DATABASE_URL)%'
            magneticod:
                driver: 'pdo_sqlite'
                url: '%env(resolve:MAGNETICOD_DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            magneticod:
                connection: magneticod
                mappings:
                    Magnetico:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Magnetico/Entity'
                        prefix: 'App\Magnetico'
                        alias: Magnetico

