sentry:
    options:
        send_default_pii: true
        ignore_exceptions:
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
            - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
            - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'

services:
    # TODO: update:
    # https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
