kind: pipeline
type: docker
name: build

steps:
# TODO: prepare image with necessary extensions
#  - name: build-deps
#    image: 'composer:2.3'
#    environment:
#      APP_ENV: dev
#    commands:
#      - composer install --no-progress --no-interaction --optimize-autoloader
#      - bin/console about
#      - 'bin/console lint:container'
#      - 'bin/console lint:twig'
#      - 'bin/console lint:container'
#      - 'bin/console lint:yaml'
  - name: docker-publish
    # https://github.com/drone/drone-plugin-index/blob/main/plugins/docker/original.md
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag
