index:
    path: /
    controller: App\Controller\MainController::index

torrent_show:
    path: /torrents/{id}
    controller: App\Controller\TorrentController::showTorrent
    requirements:
        method: GET
        id: '\d+'

torrent_search:
    path: /torrents/search
    controller: App\Controller\TorrentController::searchTorrent
    requirements:
        method: GET