<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250701155112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Migrate users.id and invites.id columns to GENERATED BY DEFAULT AS IDENTITY.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE users.users ALTER COLUMN id DROP DEFAULT");
        $this->addSql("ALTER TABLE users.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
        $this->addSql("DROP SEQUENCE IF EXISTS users.users_id_seq");

        $this->addSql("ALTER TABLE users.invites ALTER COLUMN id DROP DEFAULT");
        $this->addSql("ALTER TABLE users.invites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
        $this->addSql("DROP SEQUENCE IF EXISTS users.invites_id_seq");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("CREATE SEQUENCE IF NOT EXISTS users.users_id_seq");
        $this->addSql("ALTER TABLE users.users ALTER COLUMN id DROP IDENTITY IF EXISTS");
        $this->addSql("ALTER TABLE users.users ALTER COLUMN id SET DEFAULT nextval('users.users_id_seq')");
        $this->addSql("ALTER SEQUENCE users.users_id_seq OWNED BY users.users.id");
        $this->addSql("SELECT setval('users.users_id_seq', COALESCE((SELECT MAX(id) FROM users.users), 1), false)");

        $this->addSql("CREATE SEQUENCE IF NOT EXISTS users.invites_id_seq");
        $this->addSql("ALTER TABLE users.invites ALTER COLUMN id DROP IDENTITY IF EXISTS");
        $this->addSql("ALTER TABLE users.invites ALTER COLUMN id SET DEFAULT nextval('users.invites_id_seq')");
        $this->addSql("ALTER SEQUENCE users.invites_id_seq OWNED BY users.invites.id");
        $this->addSql("SELECT setval('users.invites_id_seq', COALESCE((SELECT MAX(id) FROM users.invites), 1), false)");
    }
}
